front/next.config.js
close #21
- next.configにwatch optionをつける
- https://weblion303.net/2515
- docker compose up front でpages配下いじってみてhot reloadが効くこと
- 自分のlenovoで動作するのは確認しました
=> 💫 windowsでもhot reloadするように

README.md, docker-compose.yml
close #30 
- container名を固定にする
- runしてたのをexecにする
- 実行中のコンテナ内で任意のコマンドを実行できる
以下のコマンドを順番に打って、コンテナの中で任意のコマンドを実行できることを確認してください
```bash
docker compose build front
docker compose up front
docker compose exec front sh
ls
```
=> :point_up: readmeとか修正

README.md
- firebaseを導入したので、.envファイルを作成するためのコマンドをreadmeに追加した。
=> 📄 README修正

front/package.json, front/yarn.lock
- バリデーションライブラリ yup を installした
- https://zenn.dev/longbridge/articles/8a167c53ff026c
**こいつがmainにマージされたら**下記コマンドを順番に実行して、作業ブランチで使えるようにしてください
```bash
git switch main
git fetch origin main
git pull origin main
git switch -
git merge main
docker compose up front
docker compose exec front yarn install
docker cp traveli-web-front:/home/app/node_modules/ ./front/
exit
```
=> 📦 バリデーションライブラリのinstall

README.md, front/src/components/Icons/IconCamera.tsx, front/src/components/Icons/IconEdit.tsx, front/src/components/Icons/IconHelp.tsx, front/src/components/Icons/IconLink.tsx, front/src/components/Icons/IconMenu.tsx, front/src/components/Icons/IconPlus.tsx, front/src/components/Icons/IconQr.tsx, front/src/components/Icons/IconReturn.tsx, front/src/components/Icons/IconSave.tsx, front/src/components/Icons/IconShare.tsx, front/src/components/Icons/IconSignOut.tsx, front/src/components/Icons/IconUser.tsx, front/src/components/Icons/IconViewGrid.tsx, front/src/components/Icons/IconViewList.tsx, front/src/pages/home.tsx
close #40 
-アイコンにchakra-uiのスタイルが当たるように修正
-READMEのコマンドの修正
- 以下確認してほしい部分のリスト
- アイコンのサイズ、色が変わってること
=> 🦩Iconにchakra-uiのスタイルが当たるように修正

front/.eslintrc.js, front/src/hooks/auth/useSignInAnonymously.ts, front/src/pages/user.tsx, front/src/types/db/index.ts, front/src/types/db/user/user.ts
close #36
- /user作成
- eslintの設定
/user
- 名前と画像、両方入力してsubmit
- 名前のみ入力してsubmit
- 画像のみ入力してsubmit
※画像のちらつきはTODO
=> :pig: 画像アップロード（ユーザページ）実装

front/src/components/Inputs/Input.tsx, front/src/components/Inputs/index.ts, front/src/stories/components/Buttons/Button.stories.tsx, front/src/stories/components/Buttons/ButtonIconRound.stories.tsx, front/src/stories/components/Inputs/Input.stories.tsx
close #50 
- Inputコンポーネント作成
- Storybookに追加
- http://localhost:6006/?path=/story/components-inputs-input--default
- ボーダーがある方のやつはcreate作るときに一緒に作るので、他ので使ってるボーダーない方だけ作りました
=> 👍 inputコンポーネント作成

front/src/theme/index.ts
close #63
- デフォルトで要素に当たるスタイルの修正
- 
- 以下確認してほしい部分のリスト
-文字がジャギってないこと
=> 🚲文字のジャギりを修正

front/next.config.js, front/src/components/Forms/FormUserProfile.tsx, front/src/pages/home.tsx
close #82
- なんか勝手にマージされちゃってるみたいだけど、一応ルーティングをできるとこだけした
- 勝手にマージされちゃったのでfilechangesに変更点ないです
- 今後問題が起きれば、そのとき修正でよろしくです(´;ω;｀)
- [http://localhost:3000/home](http://localhost:3000/home)のカードからidページへ
- [http://localhost:3000/user](http://localhost:3000/user)の<ボタンかhomeページへ
=> :earth_americas: ページ遷移を一部つけた

front/src/components/Forms/FormUserProfile.tsx, front/src/hooks/form/useCreateUpdateUserProfile.ts, front/src/theme/index.ts
close #89 #90 
- themeのcursorの設定削除
- front/src/components/Forms/FormUserProfile.tsxの修正
[http://localhost3000/user](http://localhost3000/user)
- devToolにてクリック時の適用範囲が適切になってるか
- ユーザの情報を編集時、保存されているか
=> :cow: /userの不具合を治す

front/src/components/Cards/CardLink.tsx, front/src/pages/home.tsx
-CardLinkコンポーネントを作成
- 以下確認してほしい部分のリスト
=> 🥐CardLinkコンポーネントを作成

front/package.json, front/src/components/Inputs/InputDate.tsx, front/src/theme/index.ts, front/yarn.lock
close #103
- downgradeした
- ついでにcreateのエラーも直した
- yarn installしてください
- エラーとかないか確認お願いします
=> 🥦 React18のエラーえぐくて草

front/public/images/icons/bookmark-outline.svg, front/public/images/icons/bookmark-solid.svg, front/src/components/Cards/CardHome.tsx, front/src/components/Cards/index.ts, front/src/components/Tabs/TabHome.tsx, front/src/components/Tabs/index.ts, front/src/hooks/button/index.ts, front/src/hooks/button/useButtonBookmark.ts, front/src/hooks/firestore/bookmark/useCheckBookmarked.ts, front/src/hooks/firestore/bookmark/useCreateBookmark.ts, front/src/hooks/firestore/bookmark/useDeleteBookmark.ts, front/src/hooks/firestore/bookmark/useGetBookmarkList.ts, front/src/hooks/firestore/index.ts, front/src/pages/[traveliId]/index.tsx, front/src/pages/home.tsx, front/src/theme/colors.ts, front/src/types/db/bookmark.ts, front/src/types/db/index.ts
close #105
- 保存機能を作った
- profilesに紐づけて、bookmarksコレクションを作っています
- 細かくコンポーネントに切った
- http://localhost:3000/1A2k63WZwikH76GBE6xB
- http://localhost:3000/t0TfIulyz1bP3i4fjbfl
- 上記のようなidページで保存するを押して、
- に正しく表示されるかどうか
- 保存を消した時に、homeから消えるかどうか
=> 📘  保存機能を作る

front/src/components/Cards/CardEdit.tsx, front/src/components/Cards/CardEditWrapper.tsx, front/src/components/Cards/CardLink.tsx, front/src/components/Forms/FormCreateUpdateLinks.tsx, front/src/components/Radios/RadioCategoryItem.tsx, front/src/components/Radios/RadioCategoryList.tsx, front/src/components/Radios/index.ts, front/src/hooks/form/useFormCreateUpdateLinks.ts, front/src/hooks/radio/index.ts, front/src/hooks/radio/useRadioCategory.ts, front/src/pages/[traveliId]/index.tsx, front/src/types/db/index.ts, front/src/types/db/travelink.ts
close #107, close #132, close #124
- カテゴリー機能の実装
- カスタムラジオぼたんをreact hook formに組み込むのがむずかったので、一旦useStateでゴリ押しました
- refactorのタスクとしてissueにしてます
- マークアップの修正
- http://localhost:3000/create
- http://localhost:3000/A3unCt1Xf95pAd9uEt4i/edit
=> 🥫 カテゴリー機能の実装

front/src/components/Cards/CardHome.tsx, front/src/components/Forms/FormUserProfile.tsx, front/src/hooks/filter/index.ts, front/src/hooks/filter/useFilterTravelink.ts, front/src/pages/[traveliId]/index.tsx
close #109
- next.jsのLinkコンポーネントはこコンポーネントにrefを渡すらしいので、子コンポーネントをchakra uiのlinkにした
- カテゴリ分類でコンソールエラー出てたので修正した
- http://localhost:3000
- http://localhost:3000/user
- http://localhost:3000/A3unCt1Xf95pAd9uEt4i/edit
- http://localhost:3000/A3unCt1Xf95pAd9uEt4i/
=> 🇪🇷 コンソールエラーの修正

front/src/components/Modals/ModalQrCode.tsx
close #179 
- QRコード中央のアイコンを削除
- http://localhost:3000/rLFJgWz7RKB4Qg2d6QpG
- 以下確認してほしい部分のリスト
- QRコードが読み取れること
=> 🕓QRコード中央のアイコンを削除

front/.storybook/main.js, front/package.json, front/src/stories/components/Modals/ModalQrCode.stories.tsx
close #197
- 設定を追加
- mergeしないと確認できないので，localで画像が表示されていることが確認できたらapproveほしい！
=> 👿 build後のStorybookに画像を表示させる

front/src/components/Cards/CardLinkEdit.tsx, front/yarn.lock
close #202
- GURUGURUを真ん中にした
- Q. すこし右にずれていませんか？
- A. 気のせいです。
=> 👍  ぐるぐるを真ん中にする

front/src/pages/[traveliId]/index.tsx
close #167 
- canEditがtrueもしくはownerの場合、editボタンをつける
- canEditがfalseのURL
- http://localhost:3000/e3NYJbrxpNcKN2YVRLBM
- canEditがtrueのURL
- http://localhost:3000/xmtvaRt1eIO9OFR9ZKoM
- 自分がownerの場合のリンクも作って確認お願いします
=> editできる人だけeditボタンを表示する

front/vercel.json
=> 旧ドメインから新ドメインへのリダイレクトの設定
